version: 2
jobs:
  build:
    docker:
      - image: golang:latest

    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run:
          name: Run tests 
          command: |
            go test -v ./...
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag helloworld $DOCKER_HUB_USER_ID/helloworld:latest
            docker push $DOCKER_HUB_USER_ID/helloworld:latest