version: 2
jobs:
  build:
    docker:
      - image: golang:latest

    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run:
          name: Run tests 
          command: |
            go test -v ./...
      - deploy:
          name: Publish application to docker hub
          branch: master
          command: |
            curl -H "Content-Type:application/json" -X POST https://registry.hub.docker.com/u/snowstormkitten/helloworld/trigger/cef07b88-b290-43be-ba26-cd76075609e7/