version: 2
jobs:
  build:
    docker:
      - image: golang:latest

    working_directory: /app
    steps:
      - checkout
      - run:
          name: Run tests 
          command: |
            go test -v ./...
  deployment:
    docker:
      - image: goland:latest
    working_directory: /app
    steps:
      - deploy:
          name: Run if test pass and branch is Master
          command: |
            curl -H "Content-Type:application/json" -X POST https://registry.hub.docker.com/u/snowstormkitten/helloworld/trigger/cef07b88-b290-43be-ba26-cd76075609e7/

workflows:
    version: 2

    build_test_deploy:
      jobs:
        - build
        - deployment:
          requires:
            - build
          filters:
            branches:
              only: master